AGENT_CARDS = {
    "narrative-intelligence": {
        "name": "Narrative Intelligence Agent",
        "fqan": "narrativeos.cognitive.narrative-intelligence",
        "version": "0.1.0",
        "description": "Detects emerging financial narratives, clusters topics, and tracks narrative momentum.",
        "capabilities": ["topic_clustering", "narrative_segmentation", "entity_extraction", "momentum_tracking"],
        "endpoints": {
            "analyze": "/api/v1/agents/narrative-intelligence/analyze",
            "health": "/api/v1/agents/narrative-intelligence/health",
        },
        "input_schema": "NarrativeEvent",
        "output_schema": "TopicCluster[]",
        "dependencies": [],
    },
    "sentiment-reasoning": {
        "name": "Sentiment Reasoning Agent",
        "fqan": "narrativeos.cognitive.sentiment-reasoning",
        "version": "0.1.0",
        "description": "Analyzes emotional direction, crowd psychology, and sentiment polarity from financial narratives.",
        "capabilities": ["polarity_scoring", "emotional_intensity", "uncertainty_analysis", "crowd_sentiment"],
        "endpoints": {
            "analyze": "/api/v1/agents/sentiment-reasoning/analyze",
            "health": "/api/v1/agents/sentiment-reasoning/health",
        },
        "input_schema": "NarrativeEvent[]",
        "output_schema": "SentimentVector",
        "dependencies": ["narrative-intelligence"],
    },
    "debate-bull": {
        "name": "Bull Debate Agent",
        "fqan": "narrativeos.cognitive.debate-bull",
        "version": "0.1.0",
        "description": "Argues the optimistic market case with fundamental and technical evidence.",
        "capabilities": ["bull_case_construction", "fundamental_analysis", "technical_analysis"],
        "endpoints": {
            "debate": "/api/v1/agents/debate/bull",
            "health": "/api/v1/agents/debate/bull/health",
        },
        "input_schema": "DebateContext",
        "output_schema": "DebatePosition",
        "dependencies": ["narrative-intelligence", "sentiment-reasoning"],
    },
    "debate-bear": {
        "name": "Bear Debate Agent",
        "fqan": "narrativeos.cognitive.debate-bear",
        "version": "0.1.0",
        "description": "Argues the pessimistic market case with risk-focused and contrarian evidence.",
        "capabilities": ["bear_case_construction", "risk_analysis", "contrarian_signals"],
        "endpoints": {
            "debate": "/api/v1/agents/debate/bear",
            "health": "/api/v1/agents/debate/bear/health",
        },
        "input_schema": "DebateContext",
        "output_schema": "DebatePosition",
        "dependencies": ["narrative-intelligence", "sentiment-reasoning"],
    },
    "debate-arbiter": {
        "name": "Arbiter Debate Agent",
        "fqan": "narrativeos.cognitive.debate-arbiter",
        "version": "0.1.0",
        "description": "Evaluates bull and bear arguments, identifies logical strengths, and delivers a final ruling.",
        "capabilities": ["argument_evaluation", "consensus_building", "confidence_weighting"],
        "endpoints": {
            "arbitrate": "/api/v1/agents/debate/arbitrate",
            "health": "/api/v1/agents/debate/arbiter/health",
        },
        "input_schema": "DebateRound[]",
        "output_schema": "DebateSummary",
        "dependencies": ["debate-bull", "debate-bear"],
    },
    "risk-intelligence": {
        "name": "Risk Intelligence Agent",
        "fqan": "narrativeos.cognitive.risk-intelligence",
        "version": "0.1.0",
        "description": "Evaluates systemic uncertainty, misinformation risk, and signal reliability.",
        "capabilities": ["anomaly_detection", "misinformation_analysis", "confidence_degradation", "volatility_forecasting"],
        "endpoints": {
            "assess": "/api/v1/agents/risk/assess",
            "health": "/api/v1/agents/risk/health",
        },
        "input_schema": "AnalysisSignal",
        "output_schema": "RiskAssessment",
        "dependencies": ["narrative-intelligence", "sentiment-reasoning", "debate-arbiter"],
    },
    "strategy": {
        "name": "Strategy Agent (Portfolio Manager)",
        "fqan": "narrativeos.cognitive.strategy",
        "version": "0.1.0",
        "description": "Generates final trading signals from synthesized multi-agent reasoning.",
        "capabilities": ["signal_generation", "position_sizing", "confidence_weighted_ranking"],
        "endpoints": {
            "generate": "/api/v1/agents/strategy/generate",
            "health": "/api/v1/agents/strategy/health",
        },
        "input_schema": "SynthesizedAnalysis",
        "output_schema": "AnalysisSignal",
        "dependencies": ["narrative-intelligence", "sentiment-reasoning", "debate-arbiter", "risk-intelligence"],
    },
    "market-correlation": {
        "name": "Market Correlation Agent",
        "fqan": "narrativeos.cognitive.market-correlation",
        "version": "0.1.0",
        "description": "Identifies secondary tickers, sectors, or asset classes impacted by the primary narrative.",
        "capabilities": ["cross_asset_correlation", "sector_rotation", "spillover_effects"],
        "endpoints": {
            "correlate": "/api/v1/agents/market-correlation/correlate",
            "health": "/api/v1/agents/market-correlation/health",
        },
        "input_schema": "NarrativeEvent[]",
        "output_schema": "CorrelationMatrix",
        "dependencies": ["narrative-intelligence"],
    },
    "visualization": {
        "name": "Visualization Agent",
        "fqan": "narrativeos.cognitive.visualization",
        "version": "0.1.0",
        "description": "Generates visual charts and Superplane canvas components from structured reasoning data.",
        "capabilities": ["chart_generation", "canvas_rendering", "dashboard_updates"],
        "endpoints": {
            "render": "/api/v1/agents/visualization/render",
            "health": "/api/v1/agents/visualization/health",
        },
        "input_schema": "AnalysisSignal",
        "output_schema": "VisualizationPayload",
        "dependencies": ["strategy"],
    },
    "data-acquisition": {
        "name": "Data Acquisition Agent",
        "fqan": "narrativeos.data.data-acquisition",
        "version": "0.1.0",
        "description": "Orchestrates Apify tasks and crawls external sources for financial events.",
        "capabilities": ["apify_orchestration", "web_scraping", "event_ingestion"],
        "endpoints": {
            "ingest": "/api/v1/agents/data-acquisition/ingest",
            "health": "/api/v1/agents/data-acquisition/health",
        },
        "input_schema": "IngestionConfig",
        "output_schema": "NarrativeEventBatch",
        "dependencies": [],
    },
}
